import { FileText } from 'lucide-react';
import type { Segment } from '../types';
import { getSegmentStyle } from '../lib/segmentStyles';

interface SegmentViewProps {
  segments: Segment[];
}

/**
 * Render inline markdown-style emphasis without garish colors.
 * Supports **bold** and *italic* markers.
 */
function InlineMarkdown({ text }: { text: string }) {
  if (!text) return null;

  const boldParts = text.split(/(\*\*.*?\*\*)/g);

  return (
    <>
      {boldParts.map((part, idx) => {
        if (part.startsWith('**') && part.endsWith('**')) {
          return <strong key={idx} className="font-semibold text-slate-900">{part.slice(2, -2)}</strong>;
        }

        const italicParts = part.split(/(\*[^*]+\*)/g);
        return italicParts.map((subPart, subIdx) => {
          const key = `${idx}-${subIdx}`;
          if (subPart.startsWith('*') && subPart.endsWith('*')) {
            return <em key={key} className="italic text-slate-700">{subPart.slice(1, -1)}</em>;
          }
          return <span key={key}>{subPart}</span>;
        });
      })}
    </>
  );
}

function cleanSpeakerName(speaker: string | null | undefined): string {
  if (!speaker) return 'Unknown Speaker';
  return speaker
    .replace(/\*\*/g, '')
    .replace(/^[,\s]+/, '')
    .trim();
}

function extractSpeakerNote(text: string): { name: string; note: string; rest: string } {
  // Try to find honorific prefix pattern: e.g., "श्री नफ़ीसुल हसन" or "माननीय श्री ..."
  // Return name and any trailing note in parentheses
  const noteMatch = text.match(/\(([^)]+)\)/);
  if (noteMatch) {
    return {
      name: text.replace(noteMatch[0], '').trim(),
      note: noteMatch[1].trim(),
      rest: '',
    };
  }
  return { name: text, note: '', rest: '' };
}

function renderMemberList(segment: Segment) {
  // Prefer structured members array generated by the pipeline.
  const entries = segment.members;

  if (entries && entries.length > 0) {
    return (
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-x-6 gap-y-2">
        {entries.map((entry, idx) => (
          <div key={idx} className="flex items-baseline gap-2 text-sm">
            <span className="hindi-text text-slate-800">{entry.name}</span>
            {entry.honorific && (
              <span className="text-xs text-slate-500 hindi-text">{entry.honorific}</span>
            )}
          </div>
        ))}
      </div>
    );
  }

  // Fallback: parse the raw text.
  const protectedText = (segment.text || '').replace(/माननीय\s+श्री/g, 'माननीय_श्री');
  const parsed = protectedText
    .split(/(?<=श्री|श्रीमती|माननीय_श्री|राजा|नवाब)\s+/)
    .map((e) => e.replace(/माननीय_श्री/g, 'माननीय श्री').trim())
    .filter((e) => e && !e.match(/^[:|_-]+$/) && e.length > 2);

  if (parsed.length === 0) {
    return <p className="hindi-text text-slate-800"><InlineMarkdown text={segment.text || ''} /></p>;
  }

  return (
    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-x-6 gap-y-2">
      {parsed.map((entry, idx) => {
        const match = entry.match(/^(.*?),?\s*(श्री|श्रीमती|माननीय श्री|राजा|नवाब)$/);
        const name = match ? match[1].trim() : entry;
        const honorific = match ? match[2] : null;
        if (!name) return null;

        return (
          <div key={idx} className="flex items-baseline gap-2 text-sm">
            <span className="hindi-text text-slate-800">{name}</span>
            {honorific && (
              <span className="text-xs text-slate-500 hindi-text">{honorific}</span>
            )}
          </div>
        );
      })}
    </div>
  );
}

export function SegmentView({ segments }: SegmentViewProps) {
  if (!segments || segments.length === 0) {
    return (
      <div className="text-center py-16 text-slate-500 bg-slate-50 rounded-lg border border-dashed border-slate-300">
        <FileText size={48} className="mx-auto mb-4 opacity-50" />
        <p>No content available for this page.</p>
      </div>
    );
  }

  return (
    <div className="space-y-8">
      {segments.map((segment, index) => {
        const key = `${segment.type}-${segment.start_index}-${index}`;

        // Metadata: small, muted
        if (segment.type === 'metadata') {
          return (
            <p key={key} className="text-sm text-slate-500 hindi-text">
              <InlineMarkdown text={segment.text} />
            </p>
          );
        }

        // Headings: clean, centered, large
        if (segment.type === 'heading') {
          return (
            <h2
              key={key}
              className="text-center text-xl md:text-2xl font-bold text-slate-900 hindi-heading py-2"
            >
              <InlineMarkdown text={segment.text} />
            </h2>
          );
        }

        // Announcements: simple notice block
        if (segment.type === 'announcement') {
          return (
            <div key={key} className="border-l-4 border-amber-400 bg-amber-50/50 pl-4 py-1">
              <p className="text-xs font-semibold uppercase tracking-wide text-amber-800 mb-1">
                {segment.subtype || 'Announcement'}
              </p>
              <p className="hindi-text text-slate-800 leading-relaxed">
                <InlineMarkdown text={segment.text} />
              </p>
            </div>
          );
        }

        // Member lists
        if (segment.type === 'member_list') {
          return (
            <div key={key} className="border-t border-b border-slate-200 py-4">
              <p className="text-xs font-semibold uppercase tracking-wide text-slate-500 mb-3">
                Members
              </p>
              {renderMemberList(segment)}
            </div>
          );
        }

        // Narrative / stage directions
        if (segment.type === 'narrative') {
          return (
            <p
              key={key}
              className="text-slate-600 hindi-text leading-relaxed italic"
            >
              <InlineMarkdown text={segment.text} />
            </p>
          );
        }

        // Speech: Hansard style
        const speakerName = cleanSpeakerName(segment.speaker);
        const { name, note } = extractSpeakerNote(speakerName);
        const style = getSegmentStyle('speech');

        return (
          <article key={key} className="">
            <div className="mb-3">
              <h3 className="font-bold text-slate-900 hindi-heading text-base md:text-lg">
                {name}
              </h3>
              {note && (
                <p className="text-sm text-slate-500 hindi-text mt-0.5">({note})</p>
              )}
            </div>
            <div
              className="hindi-text text-slate-800 leading-relaxed text-base space-y-4 pl-0 md:pl-4"
              style={{ borderLeft: `2px solid ${style.borderColor}` }}
            >
              <p className="pl-4">
                <InlineMarkdown text={segment.text} />
              </p>
            </div>
          </article>
        );
      })}
    </div>
  );
}
